config/routes.rb
Rails.application.routes.draw do
  resources :site_contents do
    patch :order_up, on: :member
    patch :order_down, on: :member
  end
end

app/models/site_content.rb
class SiteContent < ApplicationRecord
  default_scope -> { order(order_number: :asc) }
  has_one_attached :image
  belongs_to :parent, class_name: 'SiteContent', optional: true
  has_many :children, class_name: 'SiteContent', foreign_key: 'parent_id', dependent: :destroy
  enum type: [:nav_logo, :teaser_image, :teaser_text, :text, :image, :image_gallery]
  attr_accessor :parent_type
  enum site: CompactCms.sites
  enum language: CompactCms.languages || [:fi]
  self.inheritance_column = :type_
  
  before_create :set_order_number
  
  def set_order_number
    self.order_number ||= SiteContent.maximum(:order_number).to_i + 1
  end
  
  include SiteContent::Ordering
  
  def editable?
    type != 'image_gallery'
  end
  
end

app/models/site_content/ordering.rb
module SiteContent::Ordering
  
  def change_order change
    
    return if parent_id.blank? && site.blank?
    
    original_order_number = order_number
    direction = change > 0 ? '>' : '<'
    
    if parent_id.present?
      where_query = { parent: parent }
    elsif site.present?
      where_query = { site: site }
    end
    
    siblings = SiteContent.where(**where_query)
    new_order_number = siblings.where('order_number '+direction+' ?', original_order_number)
    new_order_number = change > 0 ? new_order_number.minimum(:order_number) : new_order_number.maximum(:order_number)
    relation = siblings.where(order_number: new_order_number)
    
    return if new_order_number.blank?
    relation&.update order_number: original_order_number
    update order_number: new_order_number
    
  end
  
end

app/controllers/site_contents_controller.rb
class SiteContentsController < ApplicationController
  include DefaultActions

  def new
    form model.new(params.permit(:site, :type, :parent_type, :parent_id, :order_number))
  end
  
  def after_save r
    after_commit r
  end
  
  def permitted_params
    params.require(model.name.underscore.gsub('/', '_').to_sym).permit([:parent_id, :parent_type, :order_number, permit_fields(model::Fields::TEXT_FORM_FIELDS), permit_fields(model::Fields::IMAGE_FORM_FIELDS)])
  end
  
  def after_destroy r
    after_commit r
  end
  
  def save record
    params_ = permitted_params
    if params_[:parent_type].present?
      parent = SiteContent.create(type: permitted_params[:parent_type], site: params_.delete(:site))
    elsif params_[:parent_id].present?
      params_.delete(:site)
    end
    record.assign_attributes params_
    if record.type == 'text' && CompactCms.languages.present? && I18n.locale.in?(CompactCms.languages)
      record.language = I18n.locale
    end
    if record.type == 'text' && record.text.present?
      doc = Nokogiri::HTML(record.text)
      doc.css('p').find_all.each do |p|
        p.remove if p.content.blank?
      end
      record.text = doc.at('body').inner_html if doc.at('body').present?
    end
    record.parent = parent if parent.present?
    authorize record
    if record.save
      result = after_save record
      unless result.present? && result.key?(:redirect) && !result[:redirect]
        redirect_to action: :index
      end
    else
      form record
    end
  end
  
  def after_commit r
    redirect_to request.referrer
    { redirect: false }
  end
  
  def form record
    authorize record
    @site_content = record
    render :form, layout: false
  end
  
  def order_up
    change_order 1
  end
  
  def order_down
    change_order -1
  end
  
  def change_order change
    record = SiteContent.find params[:id]
    authorize record
    record.change_order change
    head :ok
  end
  
end

app/helpers/site_content/form_helper.rb
module SiteContent::FormHelper
  
  def site_content_image_form record
    attachment = record.image
    if false && attachment.attached?
      link_to 'delete', delete_attachment_path(attachment.id), method: :delete, **are_you_sure_confirm, class: 'site-content-delete-button'
    else
      form_for record, html: { class: 'site-content-form' } do |f|
        concat f.file_field :image, multiple: false, direct_upload: false
        concat f.hidden_field :type
        concat f.hidden_field :site
        concat f.hidden_field :order_number
        concat f.submit 'save', class: attachment.attached? ? '' : 'alone'
        concat delete_button(record) if attachment.attached?
      end
    end
  end
  
  def site_content_text_form record, **options
    form_for record, html: { class: 'site-content-form site-content-text-form' } do |f|
      concat f.text_area :text, data: options.slice(:editable)
      concat f.hidden_field :type
      concat f.hidden_field :site
      concat f.hidden_field :order_number
      concat (tag.div class: 'buttons' do
        concat f.submit 'save'
        concat tag.span 'close', class: 'close-button'
      end)
    end
  end
  
end

app/views/site_contents/_index.html.erb
<section class="site-content-elements <%= klass if defined?(klass) %>">
  <% SiteContent.all.where(site: page, type: [:text, :image_gallery]).order(order_number: :asc).each do |site_content| %>
    <% edit_path = current_user.present? ? edit_site_content_path(site_content) : nil %>
    <article data-form-url="<%= edit_path %>" class="<%= site_content.type %> <%= 'editing' if current_user.present? %>">
      <div class="content">
        <% if site_content.type == 'text' %>
          <%= site_content.text.html_safe %>
        <% elsif site_content.type == 'image_gallery' %>
          <% site_content.children.each do |image_content| %>
            <% figure_edit_path = current_user.present? ? edit_site_content_path(image_content) : nil %>
            <figure data-form-url="<%= figure_edit_path %>">
              <%= image_tag image_content.image if image_content.image.attached? %>
              <% if image_content.text&.strip.present? %>
                <div class="black-layer"></div>
              <% end %>
              <h2 class="<%= 'short' if image_content.text&.strip&.count(' ') < 3 %>"><%= image_content.text %></h2>
              <% if current_user.present? %>
                <div class="buttons">
                  <%= tag.i 'edit', class: 'edit-button material-icons' %>
                  <%= link_to 'delete', site_content_path(image_content), method: :delete, class: 'material-icons delete-button', **are_you_sure_confirm %>
                  <%= link_to 'keyboard_arrow_down', order_up_site_content_path(image_content), method: :patch, class: 'material-icons order-up', remote: true %>
                  <%= link_to 'keyboard_arrow_up', order_down_site_content_path(image_content), method: :patch, class: 'material-icons order-down', remote: true %>
                </div>
              <% end %>
            </figure>
          <% end %>
          <% if current_user.present? %>
            <figure class="add">
              <%= tag.span('add', class: 'plus-button button',
                    data: { url: new_site_content_path(site: page, type: 'image', parent_id: site_content.id) }) %>
            </figure>
          <% end %>
        <% end %>
      </div>
      <% if current_user.present? %>
        <div class="edit-buttons">
          <%= tag.i 'edit', class: 'edit-button material-icons' if site_content.editable? %>
          <%= link_to 'delete', site_content_path(site_content), method: :delete, class: 'material-icons delete-button', **are_you_sure_confirm %>
          <%= link_to 'keyboard_arrow_down', order_up_site_content_path(site_content), method: :patch, class: 'material-icons order-up', remote: true %>
          <%= link_to 'keyboard_arrow_up', order_down_site_content_path(site_content), method: :patch, class: 'material-icons order-down', remote: true %>
        </div>
      <% end %>
    </article>
  <% end %>
</section>

<% if current_user.present? %>

  <template id="new-site-content-template">
    <article class="new-site-content">
      <div class="add content">
        <span class="plus-button button">add</span>
      </div>
    </article>
  </template>
  
  <template id="site-content-type-selection-template">
    <article class="site-content-type-selection">
      <div class="add content">
        <%= tag.span('image', class: 'image-button material-icons button',
              data: { url: new_site_content_path(site: page, type: 'image', parent_type: 'image_gallery') }) %>
        <%= tag.span('text_fields', class: 'text-button material-icons button',
              data: { url: new_site_content_path(site: page, type: 'text') }) %>
      </div>
    </article>
  </template>
  
<% end %>

app/views/site_contents/form.html.erb
<% if @site_content.type == 'text' %>
  <%= form_for @site_content, html: { class: 'site-content-form site-content-text-form full-width general' } do |f| %>
    <%= f.trix_editor :text %>
    <%= f.hidden_field :site %>
    <%= f.hidden_field :type %>
    <%= f.hidden_field :order_number %>
    <div class="buttons">
      <%= f.submit 'save', class: 'alone' %>
      <%= delete_button(@site_content) unless @site_content.new_record? %>
    </div>
  <% end %>
<% elsif @site_content.type == 'image' %>
  <%= form_for @site_content, html: { class: 'site-content-form site-content-image-form general' } do |f| %>
    <%= f.text_field :text %>
    <%= allFormFields f, f.object, SiteContent::Fields::IMAGE_FORM_FIELDS %>
    <%= f.hidden_field :site %>
    <%= f.hidden_field :type %>
    <%= f.hidden_field :parent_id %>
    <%= f.hidden_field :parent_type %>
    <%= f.hidden_field :order_number %>
    <div class="buttons">
      <%= f.submit 'save', class: 'alone' %>
    </div>
  <% end %>
<% end %>